---
dependency:
  name: galaxy
driver:
  name: podman
  #lint: |
  #set -e
  #yamllint .
  #ansible-lint .
platforms:
  - name: instance
    image: "geerlingguy/docker-centos8-ansible:latest"
    pre_build_image: true
    privileged: true
    command: ""
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
verifier:
  name: ansible
